
server:
  adminConnectors:
    - type: http
      port: 8088

database:
  driverClass: com.mysql.cj.jdbc.Driver
  user: root
  password: novell@123
  url: jdbc:mysql://localhost:3306/configservice
  properties:
    hibernate.dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate.generate_statistics: true
    hibernate.show_sql: true
    hibernate.format_sql: true
    hibernate.hbm2ddl.auto: update
    hibernate.cache.use_second_level_cache: true
    hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
logging:
  level: INFO
  loggers:
    com.atul.configservice: DEBUG
